name: subset_bam
description: |
  Subset bam file for each taxid
keywards:
  - samtools
  - view
  - subset
  - bam
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy map containing sample information
          e.g. [ id:''test, single_end:false]
  - - bam:
        type: file
        description: BAM file of reads aligned to the pathogen genomes
        pattern: "*.{bam}"
  - - bai:
        type: file
        description: BAI file (BAM index) of BAM reads aligned to the pathogen genome
        pattern: "*.{bai}"
  - taxid_accession:
      type: list
      description: A list of acessions of a taxid
output:
  - - meta:
        type: map
        description: |
          Groovy map containing sample information
          e.g. [ id:''test, single_end:false]
  - - bam:
        type: file
        description: A subset bam file
        pattern: "*.{bam}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@LilyAnderssonLee"
